name: Chromatic

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    outputs:
      storybook-url: ${{ steps.chromatic-publish.outputs.storybookUrl}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # Version 3 of the actions/checkout action will only checkout a single commit without history by default.
        # Chromatic needs the full git history in order to track changes over time.
        # see https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: "@eqworks"

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}

      - name: Publish to Chromatic
        id: chromatic-publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: true

  storybook-pr-comment:
    needs: chromatic-deployment
    if: github.event_name == 'pull_request' && needs.chromatic-deployment.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - env:
          STORYBOOK_URL_WITH_IFRAME: ${{ needs.chromatic-deployment.outputs.storybook-url }}
        run: |
          echo "STORYBOOK_URL=${STORYBOOK_URL_WITH_IFRAME/\/iframe\.html/}" >> $GITHUB_ENV
          echo "SHA=$(git rev-parse $(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha))" >> $GITHUB_ENV

      - uses: eqworks/sticky-pull-request-comment@v2
        with:
          message: |
            ### 📚 **[Storybook preview](${{ env.STORYBOOK_URL }})** _(updated to ${{ env.SHA }})_
