name: Node.js Package - alpha tag

on:
  push:
    tags:
      - 'v*-alpha*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: '@eqworks'
          always-auth: true
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
      - run: yarn publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
          scope: '@eqworks'
          always-auth: true
      - run: yarn publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_NPM_TOKEN_PUBLISH }}
