name: Storybook Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN/token the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: "@eqworks"

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
      
      - name: Build Storybook
        run: |
          yarn build-storybook --output-dir github-pages

      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.8
        with: 
          path: github-pages
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
