name: Storybook Build & Deploy

on:
  push:
    tags:
      - 's*-alpha*' # just added for testing PURPOSES
    branches:
      - main

jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN/token the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: "@eqworks"

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
          
      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.8
        with: 
          path: github-pages
  
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
